site_name: SMSGFX
site_description: Documentation for the SMSGFX tile editor.
site_author: Nicholas Furgiuele
# site_dir: ./../dist/docs
site_dir: ./../wwwroot/docs
repo_url: https://github.com/NicDoesCode/SMSGFX
repo_name: 'GitHub'
edit_uri: 'documentation/docs/'
markdown_extensions:
    - toc:
        permalink: '#'
        baselevel: 0
nav:
    - 'Home': 'index.md'
    - 'How-to':
        - 'Create a new blank project': 'how-to/create-a-new-project.md'
        - 'Import an image as a new project': 'how-to/import-an-image-as-a-new-project.md'
    - 'Application': 
        - 'User interface': 'interface.md'
        - 'Tile editor': 'tile-editor.md'
        - 'Palette editor': 'palette-editor.md'